### ISSUE TITLE
폴더명 수정

### ISSUE THREAD

**Issue by hyosin-Jang** [GroupBy-Side-Project-GSP/GSP_frontend#1]
### Describe

- [x] presenter => container로 폴더명 수정

### Work

폴더명 수정

**Comment by lyutvs** [comment]
- [x] 할거 적기

이런 형식으로 work 작성 하시면 됩니다

**Comment by hyosin-Jang** [comment]
> * [x]  할거 적기
> 
> 이런 형식으로 work 작성 하시면 됩니다
